image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - cp back/.env back/.env.local
    - cp front/src/environment.js.dist front/src/environment.js
    - sed -i s/%%MEMO_BACK_URL%%/"$MEMO_BACK_URL"/g front/src/environment.js
    - sed -i s/%%MEMO_FRONT_URL%%/"$MEMO_FRONT_URL"/g ci/deploy/dockerfiles/nginx/symfony.conf
    - sed -i s/%%MEMO_BACK_URL%%/"$MEMO_BACK_URL"/g ci/deploy/dockerfiles/nginx/symfony.conf
    - sed -i s/%%MEMO_FRONT_URL%%/"$MEMO_FRONT_URL"/g back/.env.local
    - sed -i s/%%MEMO_DB_USER%%/"$MEMO_DB_USER"/g back/.env.local
    - sed -i s/%%MEMO_DB_PASSWORD%%/"$MEMO_DB_PASSWORD"/g back/.env.local
    - sed -i s/%%MEMO_DB_HOST%%/"$MEMO_DB_HOST"/g back/.env.local
    - sed -i s/%%MEMO_DB_DB%%/"$MEMO_DB_DB"/g back/.env.local
    - mv front ci/deploy/dockerfiles/nginx/front
    - mv back ci/deploy/dockerfiles/nginx/back
    - docker build  -t registry.gitlab.com/kadmelia/memo-clock/nginx:latest ci/deploy/dockerfiles/nginx
    - docker push registry.gitlab.com/kadmelia/memo-clock/nginx:latest
    - docker build  -t registry.gitlab.com/kadmelia/memo-clock/php:latest ci/deploy/dockerfiles/php
    - docker push registry.gitlab.com/kadmelia/memo-clock/php:latest